### ISSUE TITLE
Estimation Cards can get stuck in an up/down animation loop for certain cursor placements

### ISSUE THREAD

**Issue by jhays-nhaschools** [cschleiden/azure-boards-estimate#18]
**Actual:**
When running an estimation session, place the cursor near the bottom of a voting card.

1) When moving the cursor horizontally across the bottom of the card it creates an animation loop.

2) Adjust the cursor up and down until you find a spot where the animation gets stuck in an infinite up/down loop.
![image](https://user-images.githubusercontent.com/43037440/55325806-181c3a80-5454-11e9-8d54-437a87dc3e4e.png)

**Expected:**
No such infinite up/down loop is possible. The card animation is smooth, even when moving the cursor horizontally along the bottom of the card.

**Comment by cschleiden** [comment]
Thanks for reporting. However, I don't have the capacity to fix this in version 1. Version 2 uses a different way of displaying the cards that should not show this behavior.
