### ISSUE TITLE
V2 : set of cards missing 100

### ISSUE THREAD

**Issue by RafaelKoch** [cschleiden/azure-boards-estimate#20]
Hi,

not that we are very fond of this card :-) But for some things this will be missed.
Maybe resolved when #11 is implemented.

**Comment by bryder08** [comment]
0.5 is also missing from what was there in V1.
Have been asked by our team, please can we have it back?
Modified Fibonacci Sequence: 0, ½, 1, 2, 3, 5, 8, 13, 20, 40, 100
