### ISSUE TITLE
Add context menu option to start session from backlog/query result

### ISSUE THREAD

**Issue by Russweb** [cschleiden/azure-boards-estimate#23]

**Comment by tsmccartan** [comment]
I also have this issue.  I installed it in our online DevOps.  I enabled the Preview Feature for Estimate 2.0, but now the Estimate in the Context Menu is no longer there.  I uninstalled and reinstalled.  If I disable the Preview Feature, the Estimate Context Menu shows up, but re-enabling Preview Feature and it goes away.  The Estimate Tab in the Boards view is there and working.  But you can't estimate a workitem without it in the Context Menu.
