### ISSUE TITLE
Support OnPrem TFS

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/azure-boards-estimate#3]

**Comment by souchprod** [comment]
Still alive? I have some hope as I can see a recent commit, really need this extension to avoid the temptation for a switch to competitors like Atlassian by my n+1 :'(

**Comment by cschleiden** [comment]
@souchprod Yep, see latest images here:
https://twitter.com/cschleiden

Getting close(er) :)

**Comment by souchprod** [comment]
Awesome

**Comment by olivierhelin** [comment]
Good news! We expect to setup it for over a year on our on-premise DevOps :)

**Comment by souchprod** [comment]
up

**Comment by danielstefanescu** [comment]
+1

**Comment by cschleiden** [comment]
Version 2 does work for on prem Azure DevOps Server.
