### ISSUE TITLE
V2 : estimate from a query - sorting

### ISSUE THREAD

**Issue by RafaelKoch** [cschleiden/azure-boards-estimate#33]
Sorting of original query gets lost when creating an estimate from a query.

**Comment by pabrams** [comment]
Did you repro?  I thought it maintained the sort order when I was using it.

**Comment by cschleiden** [comment]
I did, the query order is correctly returned, but then when I resolve the work items, our work items batch API returns them in ascending order by ID, and I don't think I maintain the query order. Should be an easy fix, though
