### ISSUE TITLE
Allow users to un-vote

### ISSUE THREAD

**Issue by jhays-nhaschools** [cschleiden/azure-boards-estimate#35]
After a user has voted, the user should be able to click on the same estimation card to remove their previous vote.

**Comment by sibbl** [comment]
We're also absolutely missing this feature. It's not uncommon that during discussion about a work item, things come up, which lead to the fact that you want to un-vote and wait for the end of a discussion to vote again. We always used "if everyone has casted his vote, we can reveal all" rule which is now not working anymore.

**Comment by cschleiden** [comment]
This is now implemented - see linked commit. 

Users can click their selected card again to "un-vote".
