### ISSUE TITLE
V2: Add/move reveal button to bottom

### ISSUE THREAD

**Issue by dlichterman** [cschleiden/azure-boards-estimate#36]
With the V2 preview the reveal button is at the top with the backlog or bug title. For items with lengthy descriptions or screenshots, this means that after voting, I have to scroll back up top to reveal it and scroll back down to see the results. A second button or moving it to the bottom with the cards would be incredibly helpful.

**Comment by cschleiden** [comment]
Fair, I can see how that happens.

**Comment by topher-slalom** [comment]
I agree with this, a second button at the bottom, and/or the ability to collapse the sections would be a big help

**Comment by dwballance** [comment]
My thought exactly! I'd love to see the/a button available near the cards.

**Comment by Babiarzmt** [comment]
I think moving this button to the bottom is the correct solution to this issue, as my team faced the same issue using Estimation 2 for the first time this week. Would love a quick fix here.
