### ISSUE TITLE
Clicking Hyperlinked Story ID Loads in Same Tab and Rejects CTRL-Click

### ISSUE THREAD

**Issue by Janus081** [cschleiden/azure-boards-estimate#39]
When in an estimation session and clicking the hyperlinked User Story ID at the top of the current story in focus, it loads the story within the same tab and kicks you out of the estimation session. 

It also does not allow the user to ctrl-click to open into a new tab (does nothing).

Current workaround is to right-click and select 'Open in New Tab' if you wish to view additional detail above and beyond the story description.

**Comment by cschleiden** [comment]
Are you talking about version 2 or 1? In 2 the work item should at least open in a dialog

**Comment by Janus081** [comment]
v2

Clicking the hyperlink as-is opens it in the same tab as the active estimation session thus kicking you out and forcing you to hit 'Back'

If you try to CTRL-CLICK it does not register at all.

The only solution ive found is to right click to get the menu and select 'Open in New Tab'

**Comment by cschleiden** [comment]
Hm, I just tried:

![image](https://user-images.githubusercontent.com/2201819/56004152-9b246880-5c7e-11e9-9145-06d9c635966d.png)

Are you sure your dialog is not set to cover the whole window?

![image](https://user-images.githubusercontent.com/2201819/56004169-a8415780-5c7e-11e9-8756-0e89fdc74ba9.png)

Not honoring control-click is a bug, I agree
