### ISSUE TITLE
V2 - Option to restrict item selection and card flip to organiser only

### ISSUE THREAD

**Issue by bryder08** [cschleiden/azure-boards-estimate#43]
Previously in V1, only the organiser could change the selected work item , flip the cards and select an updated score.
In V2 all members scoring are able to carry out any action within the session, causing a number of issues. E.g. accidently clicking a different work item and resetting all scores.

Please could we have an option when the estimation session is created for the overall control to be with the organiser only on/off?

**Comment by MikeWilliams-UK** [comment]
This sounds similar to https://github.com/cschleiden/azure-boards-estimate/issues/63

**Comment by cschleiden** [comment]
About to release a new version that will allow this:
![image](https://user-images.githubusercontent.com/2201819/63894954-bd572280-c9a2-11e9-98e5-5db6524ef8f8.png)
