### ISSUE TITLE
V2.0.7 - Users get Symbol is undefined error

### ISSUE THREAD

**Issue by aaronweech** [cschleiden/azure-boards-estimate#46]
Users who are using IE 11 are not able to participate in estimating sessions after the release of v2.0.7.  They are getting the following error "Could not load session: 'Symbol' is undefined"

![Symbol](https://user-images.githubusercontent.com/49757929/56368198-8b47df80-61bc-11e9-9406-0de4e3ea3eaf.JPG)

**Comment by cschleiden** [comment]
I just released v2.1.2 that contains a fix for this and other IE11 issues
