### ISSUE TITLE
Side cards should show Story Points once they've been applied to a work item

### ISSUE THREAD

**Issue by deadlydog** [cschleiden/azure-boards-estimate#47]
Currently after you do an estimate and apply Story Points to the work item, the card on the side of the screen is updated to show the newly assigned Story Points value, but only for the host; None of the other participants are able to see the value that was applied to the work item. Ideally as soon as the host applies the Story Points to the work item, it would refresh on all participants screens to show the estimate number on the work item card on the side.

**Comment by cschleiden** [comment]
This is fixed with #67 and included in the latest update. Thanks for reporting!
