### ISSUE TITLE
Estimate work items in an iteration not populating

### ISSUE THREAD

**Issue by berndku** [cschleiden/azure-boards-estimate#52]
Since about 1-2 weeks we have a problem, that the dropdown "Estimate work items in an iteration" does no longer populate, though iterations exist. 

![Screenshot](https://user-images.githubusercontent.com/4060485/57387698-1eba7200-71b7-11e9-8c15-047084a19a25.png)

In other projects of the same account, the dropdown is populated.

Any ideas ?

**Comment by cschleiden** [comment]
Any error message on the console? Or failed requests in the network tab? 

Have you tried the new version?

**Comment by berndku** [comment]
Unfortunately no errors on console/network tab.
We switched to the new version, which does not have the issue.
