### ISSUE TITLE
Add License information to extension page

### ISSUE THREAD

**Issue by pross45** [cschleiden/azure-boards-estimate#56]
Would you please add licensing information as we're unable to complete review on the extension and then use it internally within our enterprise ADO instances.

**Comment by cschleiden** [comment]
The code is licensed under the MIT license, see https://github.com/cschleiden/azure-boards-estimate/blob/master/LICENSE. 
Is that not enough?

**Comment by pross45** [comment]
Yes the MIT license is enough, but can you get that added to the marketplace extension page?  It will need to be on that page for our reviewers to pass the extension.
