### ISSUE TITLE
Cannot connect to backend

### ISSUE THREAD

**Issue by bottsrus** [cschleiden/azure-boards-estimate#57]
Version 2.0.9
Beta not turned on
I can create a plan but when I try to use it I get this error.
**An embedded page at ms-devlabs.gallerycdn.vsassets.io says**
_Could not connect to backend for real time communication, please try again._

I turned on the Beta and it never completes adding the work items when I click on the plan. I have turned the beta off again.

[Estimate.pdf](https://github.com/cschleiden/azure-boards-estimate/files/3249044/Estimate.pdf)

[Estimate 2.pdf](https://github.com/cschleiden/azure-boards-estimate/files/3249046/Estimate.2.pdf)

**Comment by juventusgle** [comment]
Any News Regarding this Issue ?

**Comment by GabK** [comment]
Servers also seem down on my end—I had to resolve to typing my estimates manually like a filthy animal.

**Comment by cschleiden** [comment]
As embarrassing as it is: my personal Azure account ran into its spending limit and the SignalR backend was stopped. New billing period starts tomorrow, service should be back up then. 

For the future I'll see if I can move that backend to a company supported subscription.

**Comment by MikeWilliams-UK** [comment]
Shame the site has to be run on a personal account.

**Comment by cschleiden** [comment]
And it's back.
