### ISSUE TITLE
Wont connect to server

### ISSUE THREAD

**Issue by MikeWilliams-UK** [cschleiden/azure-boards-estimate#58]
Yesterday when I set it up and enabled the V2 Preview it was working great.

Today I wanted to demonstrate it to a colleague I can create a session, but when I try to join it I get a permanent page showing "Connecting to server ..."

**Comment by MikeWilliams-UK** [comment]
Just turned off V2 and opened an estimating session I now get this error
![image](https://user-images.githubusercontent.com/13162784/58858985-bd47cf00-86a0-11e9-83f3-02f9d18ac7bf.png)
So it looks like a server is down...
V2 should not hang, it ought to give a similar message

**Comment by OniBait** [comment]
Looks like the signalr website got stopped: https://estimate-vso-signalr.azurewebsites.net/

**Comment by cschleiden** [comment]
Duplicate of #57
