### ISSUE TITLE
 is not working

### ISSUE THREAD

**Issue by Darlan82** [cschleiden/azure-boards-estimate#59]
Is not connecting to the server!
The screen is loading and does not run!

![image](https://user-images.githubusercontent.com/10963814/58889181-e24b3a80-86be-11e9-8246-d6678dc03fd8.png)

**Comment by OniBait** [comment]
Looks like the signalr website that is set up for this is stopped: https://estimate-vso-signalr.azurewebsites.net/

**Comment by jzworkman** [comment]
@cschleiden Does this server need to be restarted?  Estimating has not been working for 2 days now

**Comment by cschleiden** [comment]
Duplicate of #57
