### ISSUE TITLE
Allow async estimating

### ISSUE THREAD

**Issue by bryceg** [cschleiden/azure-boards-estimate#6]
A benefit would be if we can get estimates from various people without all having to be in the session at the same time.  With a global team, it would be nice to be able to request estimates to the items by a certain date and the requesters can do the estimating on their own schedule.

**Comment by cschleiden** [comment]
Thanks for the feedback, that sounds like a valuable addition

**Comment by hffourie** [comment]
We have just started using this and the above feature is definitely something we would also like to see. We want our developers to independantly look at the work items and "Pre" point them before our actual poker sessions.

**Comment by cschleiden** [comment]
@bryceg @hffourie For now I've added an offline mode. 

1. Create an offline session:
![image](https://user-images.githubusercontent.com/2201819/55271647-6cb19100-526d-11e9-8070-ad43fcf7a9e6.png)
2. Everyone can estimate at their own pace, estimates are persisted outside of the work item
3. Once everyone is done, anyone can take a look at the session, reveal the cards and commit the value to the work item:
![image](https://user-images.githubusercontent.com/2201819/55271638-4a1f7800-526d-11e9-9ec2-1530a1ffb3e4.png)

Note: initially this still relies on the "honor system". Anyone could at anytime "Reveal" the cards and see the other estimates before submitting their own. Disabling this could be a future improvement.
