### ISSUE TITLE
How to have estimate feed Story points vs Effort

### ISSUE THREAD

**Issue by alexget11** [cschleiden/azure-boards-estimate#60]
We need the planning poker estimate to feed story points not effort.  Is there a config setting for this?

**Comment by jdnickell** [comment]
We had the same requirement. At this time, we were able to update the organization's extension version to Version 2 Preview. Then, we were able to change this setting so that Story Points is updated instead of Effort. 

Similar answer: https://github.com/cschleiden/azure-boards-estimate/issues/64

**Comment by cschleiden** [comment]
See #64
