### ISSUE TITLE
Azure DevOps group controlled Reveal and Save button

### ISSUE THREAD

**Issue by pradeepyerramothu** [cschleiden/azure-boards-estimate#63]
Every team member is able to reveal the story points and save the points. Can this functionality be configurable to allow a security group in Azure DevOps. I feel like this is very important and it will avoid causing chaos and confusion. 

Thank you. fyi, the v2 looks great.

**Comment by cschleiden** [comment]
Thanks for your comment!

Can you tell me a bit more about your scenario? Do people abuse that the buttons are visible to everyone? 

My team(s) haven't used Scrum and planning poker in a long time, so any information would help.

My assumption would be, that teams use some kind of communication channel during an estimation session (Teams, Zoom, Slack, etc.) and the Scrum Master moderates the session so it should be clear when someone should/should not hit Reveal/Save, but I might be mistaken.

**Comment by pradeepyerramothu** [comment]
We have a fairly large team(both in-house and remote) that participate in planning poker. 
Just an fyi, I am referring to the online session aspect of Estimates.

**Scenario 1**:
It's not necessarily abuse but sometime one of the team member reveals the votes before everyone hasn't finished putting point on a user story. 

**Scenario 2**:
We finish pointing a user story and reveal the story points, one team member overrides the value set by the Scrum Master.

In the past, we used planningpoker.com for estimations but we need to switch back and forth from the tool and AzureDevOps to save the story points.

With the **Estimate** extension, all the story pointing can be done in one place and that's amazing and saves a lot of time.  

What i was suggesting was that if the Reveal and Save buttons are restricted to everyone except for a configured AzureDevOps security group(which typically has Scrum Master), that wouldn't be any confusion created as a result of someone else revealing or saving.

**Comment by MikeWilliams-UK** [comment]
Firstly many thanks for such an excellent extension to Azure DevOps.

We used it in anger today and are very pleased with the results. We also used some tools such as planningpoker.com and got frustrated by the need to keep switching windows to save the points.

We too feel that control of who can reveal and save the point should be controlled by security group.

We would also like to see the list of stories be controlled by the above security group as we found that the "current" story can be changed at random by anyone.

We would also like to see a re-vote button again controlled by the above security group, this would avoid the need to select a diffent story then go back to the previous one to clear the votes.

**Comment by MikeWilliams-UK** [comment]
Ab alternative to security groups might be to limit item selection, reveal and save to the person who created the session.
This is implied by the tool tip ...

![image](https://user-images.githubusercontent.com/13162784/61860388-c7789380-aec1-11e9-8248-1438dfa47140.png)

**Comment by Nardax** [comment]
Please do limit the ability to choose stories and press the reveal button to only the organizer. We often have people not paying attention to what they are clicking on or new people who don't know. This turns into a huge time waist.

**Comment by cschleiden** [comment]
Closing in favor of #43
