### ISSUE TITLE
Is it possible to feed Original Estimate field instead of story points

### ISSUE THREAD

**Issue by rezanid** [cschleiden/azure-boards-estimate#64]
Is it possible to make Estimate feed Original Estimate and not Story Points?

**Comment by cschleiden** [comment]
In version 2 you can configure the target field for every work item type in the project via the Settings panel:
![image](https://user-images.githubusercontent.com/2201819/59606191-cc9f3180-9110-11e9-9166-6ee7c8544452.png)

**Comment by jordilordan** [comment]
Can this be configured for each project? Or only in organization level?
Because I can not find the configuration on my project.

**Comment by rezanid** [comment]
Apparently we don’t have access to see the settings. I am going to ask our DevOps engineer.
