### ISSUE TITLE
Extension does not load on Azure DevOps Server

### ISSUE THREAD

**Issue by scottlezberg** [cschleiden/azure-boards-estimate#68]
We are testing Azure DevOps Server 2019 (on-premise) and am trying to evaluate the Estimates extension but cannot get it to work.  Going to Settings just hangs.  Trying to start a session wont work either.  I tried uninstalling/reinstall extension.  Any other ideas?

Thanks

Scott

**Comment by cschleiden** [comment]
@scottlezberg do you see any error messages on the console? What browser are you testing it with?

**Comment by scottlezberg** [comment]
Chrome (and Edge) - looks like this is the console error it is throwing.  I am vaguely familiar with this tag "'allow-same-origin' but this is a out of the box Azure DevOps Server 2019 installation.  Where and what would I need to fix this?

Uncaught DOMException: Failed to read the 'serviceWorker' property from 'Navigator': Service worker is disabled because the context is sandboxed and lacks the 'allow-same-origin' flag.
    at ya (https://tfs2019test.deltek.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.0.10/assetbyname/build/static/js/main.cd0695f5.chunk.js:1:80175)
    at https://tfs2019test.deltek.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.0.10/assetbyname/build/static/js/main.cd0695f5.chunk.js:1:83077
/tfs/Deltek/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/tfs/Deltek/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions-8ea6dc22-b342-48f0-8ab0-2005e84911d5/Documents:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/tfs/Deltek/_apis/projects/8ea6dc22-b342-48f0-8ab0-2005e84911d5/teams?%24top=2000:1 Failed to load resource: the server responded with a status of 404 (Not Found)
1.7edcf367.chunk.js:1 uncaught at zn at zn 
 at d 
 at Kn 
 TFS.WebApi.Exception: 404: Not Found
    at Object.<anonymous> (https://tfs2019test.deltek.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.0.10/assetbyname/build/static/js/1.7edcf367.chunk.js:1:543563)
    at https://tfs2019test.deltek.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.0.10/assetbyname/build/static/js/1.7edcf367.chunk.js:1:542086
    at Object.next (https://tfs2019test.deltek.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.0.10/assetbyname/build/static/js/1.7edcf367.chunk.js:1:542191)
    at a (https://tfs2019test.deltek.com/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/estimate/2.0.10/assetbyname/build/static/js/1.7edcf367.chunk.js:1:540936)

**Comment by cschleiden** [comment]
Ah, interesting. I haven't tried it on an onprem https setup, maybe we just need to disable the service worker for that scenario for now. I'll check, thanks.

**Comment by scottlezberg** [comment]
There might be a web.config value I can try - can you tell me what directory this extension is installed to?  I am looking all through C:\Program Files\Azure DevOps Server 2019\Application Tier\Web Services but cannot find it.

**Comment by cschleiden** [comment]
Good question, I'm not sure how we store/install the extensions onprem.

**Comment by scottlezberg** [comment]
Any progress on getting this to work on Azure DevOps Server 2019 (on-premise)?  I am still having issues

**Comment by arvindsedha** [comment]
I am having also same issue for on-premises DevOps 2019. Waiting for a fix!

**Comment by cschleiden** [comment]
Do you all have HTTPS enabled for Azure DevOps Server?

**Comment by scottlezberg** [comment]
Yes - only HTTPS is enabled

**Comment by cschleiden** [comment]
Hm.. I can't repro this locally with a Azure DevOps Server 2019 Update 1 deployment. I do get an error about the service worker not getting installed but that doesn't block the extension. I can still create and join sessions.

**Comment by scottlezberg** [comment]
I installed 2019 Update 1 RC2 and am having the same issue.

**Comment by chrismjgallant** [comment]
I'm also having the same problem. just hanging and i'm using DevOps 2019 OnPrem (2019.0.1). Any Luck? I've been waiting months hoping there would be a fix for it. Looks like a very useful feature!

**Comment by TroyHouston** [comment]
This is also blocking me from using the extension, tried re-installing and it didn't improve.

@cschleiden Is there any information I can provide to help you reproduce the issue?
My setup is similar to the above, DevOps OnPrem 2019 (Version 17.143.28621.4) using HTTPS. I have tried across Chrome, Edge (Dev) and IE11 and all have the same issue where I cannot create a session or open the settings panel.

**Comment by garnetb** [comment]
Same blocking problem for us, running OnPrem 2019 using only HTTPS

**Comment by cschleiden** [comment]
The 404 errors are expected, initially the collection used to store the session documents is empty.

**Comment by cschleiden** [comment]
Just tried again on a local installation with HTTPS enabled and while I also saw the `serviceWorker.js` errors and 404s, the extension worked just fine.

**Comment by cschleiden** [comment]
Not really sure how to proceed here further, to be honest.

**Comment by cschleiden** [comment]
Turns out that I'm using an API that for OnPrem is only available in `2019 Update 1`. I've updated the extension so that it's now correctly reflected in the marketplace.

Installing update 1 (see [release notes](https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2019u1?view=azure-devops)) should allow you to use it on premises as well.

**Comment by TroyHouston** [comment]
Thanks for the reply, it helped get further but still has issues.

After upgrading to 2019.1 OnPrem I can successfully create a session but I am unable to open it as it gives a 401 error.

![EstimateIssue30-Aug](https://user-images.githubusercontent.com/4496632/64003640-c7bf1b00-cb60-11e9-9e5b-605cffeb2975.png)

With the network response saying that the collection does not exist:
`{"$id":"1","innerException":null,"message":"%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}`

@cschleiden Is it possible that the extension only works for collections that are on the inheritance process model?

**Comment by cschleiden** [comment]
@TroyHouston Thanks for confirming that 2019.1 helps with some of the issues. I've created #86 to track the xml/inherited customization issue.
