### ISSUE TITLE
All users can see admin buttons

### ISSUE THREAD

**Issue by themanfromsql** [cschleiden/azure-boards-estimate#71]
All users in our estimation session can see the Reveal button and the End Session button. Previously, only the session initiator could see those. Also, any user clicking on another PBI will shift everyone's focus to the new PBI, blowing away any estimates already made.

**Comment by jtrout** [comment]
Yep, it's been this way the entire time it's in beta, I'm disappointed they didn't fix it before releasing.

**Comment by cschleiden** [comment]
Closing in favor or #63
