### ISSUE TITLE
Estimation session to be owned by one Team member

### ISSUE THREAD

**Issue by Sandeepjhanwar** [cschleiden/azure-boards-estimate#95]
Hello Team, 

Estimation is currently owned by all the team members but it should be own by one member only( Who start the session for the Day ).  

Issue faced: As there are several backlog work item we use to estimate and if any member click on other backlog item to view details, Estimation session goes to that team member.

Regards

**Comment by cschleiden** [comment]
See the security option during session creation, that restricts these operations to the creator of the session.
